include:
  - project: 'sasha7340122/ci2'
    ref: main
    file: 'ci_docker.yml'

.deploy_spring-backend:
  extends: .docker_run
  variables:
    IMAGE_NAME: "spring-backend"
    CONTAINER_NAME: "backend"
    ENV_FILE: ".env"

.deploy_react-frontend:
  extends: .docker_run
  variables:
    IMAGE_NAME: "react-frontend"
    CONTAINER_NAME: "frontend"
    ENV_FILE: "react-frontend/.env"
    VOLUME: "/Users/georgy/nginx-config/nginx-frontend.conf:/etc/nginx/nginx.conf"

.deploy_nginx-proxy:
  extends: .docker_run
  variables:
    IMAGE_NAME: "nginx-proxy"
    CONTAINER_NAME: "nginx_proxy"
    PORT_NUMS: "3001:3000"
    VOLUME: "/Users/georgy/nginx-config/nginx.conf:/etc/nginx/nginx.conf"

.deploy_mysql:
  extends: .docker_run
  variables:
    IMAGE_NAME: "mysql"
    CONTAINER_NAME: "db"
    ENV_FILE: ".env"
