version: "3"

services:
  nginx:
    image: my_nginx_image
    container_name: nginx_container
    build: 
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./static:/var/www/static
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "5400:5400"
    restart: unless-stopped